FROM python:3.12.3-slim-buster

LABEL maintainer="sahandmotallebii@gmail.com"

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

COPY ./requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./core .